### PR TITLE
Remove v9 + fix the Joy emoji overlapping with Thinking

### PR DESCRIPTION
**Pull request by G-4-M-3-R**

### CODE REVIEW

**Comment by BenCat07** [comment]
sad but understandable

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
esp.v952-mode needs to be removed from XML

**Review by BenCat07 — APPROVED** [review]
LGTM (+ you made some changes afterwards which suggests you actually tested it)

**Review by BenCat07 — CHANGES_REQUESTED** [review]
nevermind, see elite

**Review by TotallyNotElite — APPROVED** [review]
The atlas needs to be cleaned up anyway, change my mind

**Comment by TotallyNotElite** [comment]
> nevermind, see elite

How dare you call me that!

**Review by BenCat07 — APPROVED** [review]

**Pull request merged**
