### PR TITLE
Resolver update

### PR DESCRIPTION
**Pull request by dotqurter**
edited the bruteforce angles more so we dont dump fakedown as much because of checking +/-90 on safepoint-able angles

### CODE REVIEW

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
Please modify this pull request to only contain your personal changes without any duplicate changes.

**Comment by BenCat07** [comment]
imma rebase this i guess

**Comment by incontestableness** [comment]
so I tested this (`aab19db`) and almost all players flip around etc. a lot
it looks really funny and that's about it
sometimes when you join a match (with resolver already enabled) it'll immediately crash when rendering starts:
```
...
cathook critical_error_handler(int) /home/notroot/cathook/src/hack.cpp:133
linux-gate.so.1 0x1180
/lib/i386-linux-gnu/libc.so.6 0x14fb65
/lib/i386-linux-gnu/libc.so.6 0x14dd35
cathook BytePatch::Patch() /home/notroot/cathook/include/bytepatch.hpp:57
cathook BytePatch::Patch() /home/notroot/cathook/include/bytepatch.hpp:47
cathook DetourHook::InitBytepatch() /home/notroot/cathook/include/DetourHook.hpp:39
cathook DetourHook::RestorePatch() /home/notroot/cathook/include/DetourHook.hpp:69
cathook hacks::tf2::animfix::CheckForSequenceChange_hook(int*, int*, int, bool, bool) /home/notroot/cathook/src/hooks/PlayerAnimFix.cpp:43
/home/notroot/.steam/steam/steamapps/common/Team Fortress 2/tf/bin/client.so 0xe74559
...
```

**Comment by dotqurter** [comment]
the crash is due to a test segment of code from bencat of testing nolerp fixes

the flipping around is semi-intentional, there isnt any code pertaining to checking if the player is actually antiaiming: it just applies the resolved angles to all players. the change it makes is to ignore the player's incoming angle and restoring the bruteforced angle in an attempt to stop dumping stuff like fake static angles

**Comment by dotqurter** [comment]
i'll reset my code to master branch and reimplement the changes, and work on it at a later date

**Pull request closed without merging**
