### PR TITLE
AutoItem: replaces Achievement.cpp with autocraft and autorent system.

### PR DESCRIPTION
**Pull request by aUniqueUser**
Adds rvars for automatic test running and crafting items, replaces auto equip:

Example autocraft rvar:
59,60;44,46;38,39;5000,5000,5000;57,58,5001-642

First 3 crafting groups are getting class weapons and smelting them, next is combining scrap to make reclaimed, last is crafting the cozy camper (642)

Example rent rvar:

752/402

Trys to rent 752 (Heatmaker) then if that fails (eg item rent expired) then it trys to rent fallback item, in this case 402 (Bazaar Bargin).

### CODE REVIEW

**Comment by aUniqueUser** [comment]
Add label "hacktoberfest-accepted" if cool

**Comment by incontestableness** [comment]
oh god

**Review by BenCat07 — APPROVED** [review]
LGTM, tested aswell and fixed a bug with spy on confirmation with PR creator

**Review by TotallyNotElite — APPROVED** [review]
I don't know

**Pull request merged**
