### PR TITLE
Rewrite backtrack

### PR DESCRIPTION
**Pull request by BenCat07**
Increases hitrate immensely, also aims to lower code complexity (for modules like aimbot and triggerbot) and does "proper" backtracking, aka teleporting the entity back to where they were originally

### CODE REVIEW

**Comment by Trapacid** [comment]
I tested this and for the first match it seems to work amazingly and flawless with the aimbot aiming at backtrack ticks, a lot better and more accurate than before, but after the second match the game breaks totally with backtracking.

As soon as you pick a class, game locks up and can't seem to do anything until you turn off backtracking entirely. Turning it back on lets you continue playing, but UI elements like map timer, hit damage indicators, control point UI at the bottom, player indicators, kill feed, and map lost or won either don't pop up or they flash repeatedly.

Here are they shown:
https://streamable.com/q0k10p
https://streamable.com/f1uve0

Also, triggerbot no longer works properly being it only aims at the head regardless of the hitbox mode. It seems to be independent of the backtrack enabled option. 
Here's that shown as well:
https://streamable.com/5w3dsh

**Comment by leKamikaze1** [comment]
Gonna try this, bencat is SUPER based

**Comment by leKamikaze1** [comment]
Crashed a ton for me, while pushing the cart, falling from a cliff, or even rocketjumping. Gonna see if these issues are because of the bt_rewrite branch

**Comment by iraizo** [comment]
Closes https://github.com/nullworks/cathook/issues/1195

**Comment by iraizo** [comment]
This branch keeps on crashing when trying to aimbot any kind of building, especially dispensers

**Comment by BenCat07** [comment]
i cannot replivate This PLEASE hand in crash logs.

**Comment by iraizo** [comment]
> i cannot replicate This PLEASE hand in crash logs.

Will do next time im playing because the `report-crash` script tells me its not a cathook crash and i would need to get another log

**Comment by BenCat07** [comment]
use attach-gdb in that case

**Comment by TotallyNotElite** [comment]
What is blocking this PR? Crashes?

**Comment by leKamikaze1** [comment]
ig

**Comment by BenCat07** [comment]
> What is blocking this PR? Crashes?

i fixed a bunch and stopped getting reports

**Comment by leKamikaze1** [comment]
iirc, i sent you another report after what I think are most of the fixes in the telegram chat

**Comment by leKamikaze1** [comment]
nevermind, after my last report, softlock fix was committed

**Comment by crwn1337** [comment]
works great, but aimbot completely breaks if backtrack is disabled (tries to backtrack even if its disabled, models disappearing if you shoot)

**Comment by BenCat07** [comment]
> works great, but aimbot completely breaks if backtrack is disabled (tries to backtrack even if its disabled, models disappearing if you shoot)

Will check, because that does not make sense. Do you mean backtrack itself or "aim at backtrack"?

**Pull request merged**
