### PR TITLE
Add the thermal thruster to ignored weapons in rapidfire

### PR DESCRIPTION
**Pull request by Lewdcifer**
Added Thermal Thruster to ignore

### CODE REVIEW

**Comment by iraizo** [comment]
If you keep working on the same file put it in a single PR.

**Comment by Lewdcifer** [comment]
> If you keep working on the same file put it in a single PR.

well I only thought about adding more changes after Ive made the PR ._.

**Comment by iraizo** [comment]
Then add it to the same branch and they will get added to your old pull request

**Comment by Lewdcifer** [comment]
> > If you keep working on the same file put it in a single PR.
> 
> well I only thought about adding more changes after Ive made the PR ._.

and I'm not quite sure how github works

**Comment by BenCat07** [comment]
> > and I'm not quite sure how github works
> 
> You need to add changes to `Lewdcifer:patch-3` instead of `Lewdcifer:patch-4`

not a neccesitiy.

**Comment by iraizo** [comment]
> not a neccesitiy.

Alright

**Pull request merged**
