### PR TITLE
Check if attach is ran as root + Add Debian support to dependencycheck script

### PR DESCRIPTION
**Pull request by Trapacid**
Adds Debian support for the dependency check script which was giving me issues using Debian.

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
Something up with CI here, idk

**Comment by Trapacid** [comment]
Debian doesn’t seem to be supported due to Steam installing to .steam. Please remove Debian mentions from the catbot-setup repo.
 No need to merge.

**Comment by TotallyNotElite** [comment]
If debian support is tested on normal cathook, we can add unofficial support for it. Cathook is not software exclusively for bots.

**Comment by TotallyNotElite** [comment]
> Debian doesn’t seem to be supported due to Steam installing to .steam
We have code in place to allow this to work tho 🤔

**Comment by Trapacid** [comment]
Well, I tested normal cathook and it injects just fine and works on Debian then.

**Comment by Trapacid** [comment]
Added another commit: Check if attach is ran as root.

Some GDB commands are still ran when you don't run as root, thus trying to inject again without restarting your game causes it to crash.

**Comment by delimeats-ch** [comment]
I don’t have any issues with running attach as a non-root user. Why is this necessary?

**Comment by BenCat07** [comment]
you have some special gdb build then, because gdb does not work unless ran as root/with sudo.

**Comment by delimeats-ch** [comment]
> you have some special gdb build then, because gdb does not work unless ran as root/with sudo.

Does the attach script not re-run itself with sudo?

**Comment by BenCat07** [comment]
no

**Comment by TotallyNotElite** [comment]
Can someone explain why this PR includes @aUniqueUser's commits?

**Comment by BenCat07** [comment]
> Can someone explain why this PR includes @aUniqueUser's commits?

he didn't rebase properly.

**Comment by TotallyNotElite** [comment]
@BenCat07 mind looking into circlecli? I'm busy with #1344

**Comment by BenCat07** [comment]
kk

**Comment by Trapacid** [comment]
> Can someone explain why this PR includes @aUniqueUser's commits?

@TotallyNotElite 

If it's an issue I'll gladly redo my PR haha. Apologies.

**Comment by TotallyNotElite** [comment]
You don't need to redo your PR, please rebase onto nullworks/master and then force push.

**Comment by Trapacid** [comment]
> You don't need to redo your PR, please rebase onto nullworks/master and then force push.

@TotallyNotElite Had a totally messed up git repo so I went and made a new PR with a fresh fork, apologies. 
Should be perfect now: https://github.com/nullworks/cathook/pull/1349

**Comment by TotallyNotElite** [comment]
There is no such thing as a totally messed up repo, I would know, I'm the local git ninja of this project :)

**Pull request closed without merging**
