### PR TITLE
Fix Binding issues on Keys

### PR DESCRIPTION
**Pull request by BenCat07**

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
What issue does this fix? Please be more specific.

**Comment by BenCat07** [comment]
> What issue does this fix? Please be more specific.

I recently migrated to using the key format given out by sdl instead of tf2's, which comes with the advantage of preload not breaking keys. However i accidentally forgot the line for normal non mouse buttons, so it didn't work in the menu.

**Comment by TotallyNotElite** [comment]
I still do not understand what the purpose of this PR is. What issue is it fixing? What didn't work in the menu?

**Comment by robootgit** [comment]
Before, you couldn't bind any keys besides mouse buttons in the menu

**Pull request merged**
