### PR TITLE
Testing -> Master

### PR DESCRIPTION
**Pull request by TotallyNotElite**
Another big update for cathook! This update includes the following new features:

- Navbot followbot works properly now
- Melee aimbot accurately checks melee ranges now
- Building aimbot (Sentry, Dispenser, Teleporter) is now more accurate.
- **Partybypass now included in cathook!** [Read wiki post.](https://github.com/nullworks/cathook/wiki/What-is-Partybypass-and-how-do-I-use-it%3F)

### CODE REVIEW

**Comment by BenCat07** [comment]
no

**Comment by martsklav** [comment]
@BenCat07 no

**Comment by BenCat07** [comment]
@martsklav a

**Comment by martsklav** [comment]
index

**Comment by BenCat07** [comment]
@martsklav Test

**Comment by martsklav** [comment]
@BenCat07 test 2

**Pull request merged**
