### PR TITLE
Fix Absurdely janky projectile problems with initial velocity

### PR DESCRIPTION
**Pull request by BenCat07**

### CODE REVIEW

**Review by TotallyNotElite — DISMISSED** [review]
trust.avi

**Review by aUniqueUser — APPROVED** [review]
lgtm

**Comment by acidtripparty** [comment]
Why do we need separate calculation for initial velocity?

**Comment by BenCat07** [comment]
because we need to compensate for the fact that some projectiles start with an upwards velocity already applied, if we do not compensate for that we miss alot of shots

**Comment by acidtripparty** [comment]
Thanks for the explanation!

**Pull request merged**
