### PR TITLE
More stuff

### PR DESCRIPTION
**Pull request by NotAnUser1**
- Added the new conditions to the cheat
- Added "gassed" condition esp
- Added an option to make radar's outer border and targeted players border color change color to target color if aimbot is targeting someone
- Added more weapons to related list
- Changed projectile speed data to tf2wiki ones and de-duped it
- Changed case on powerup esp
- Changed font to Verdana

### CODE REVIEW

**Comment by Freezgam03** [comment]
Unless you added a option to make the radar change color if the aimbot is targetting someone it shouldn't be added imo.

**Comment by Stopthebots** [comment]
Please stop the bots, TF2 is now unplayable because of you guys. #Stopthebots

**Comment by TotallyNotElite** [comment]
@Stopthebots The cathook developers have no control over the bot hosters, I don't know why you are asking us about that.

**Review by TotallyNotElite — APPROVED** [review]
LGTM

**Pull request merged**
