### PR TITLE
Revert "squash your shit."

### PR DESCRIPTION
**Pull request by iraizo**
Reverts nullworks/cathook#1423

### CODE REVIEW

**Comment by d3fc0n6** [comment]
what the fuck are you guys even doing holy shit

**Comment by BenCat07** [comment]
just soft reset and commit all the changes at once holy shit

**Comment by iraizo** [comment]
> just soft reset and commit all the changes at once holy shit

Thats what i tried in my original pr but that didnt work out

**Comment by d3fc0n6** [comment]
> 
> 
> just soft reset and commit all the changes at once holy shit

this please, #1423 is a fucking disaster

**Comment by BenCat07** [comment]
@TotallyNotElite i enact a force push to master to fix this mess

**Comment by iraizo** [comment]
LOL

**Comment by delimeats-ch** [comment]
holy fuck

**Comment by iraizo** [comment]
Yes indeed

**Pull request closed without merging**
