### PR TITLE
ConfigUI

### PR DESCRIPTION
**Pull request by LightPower392**
This is a slightly tweaked version of the previous config UI branch.

### CODE REVIEW

**Comment by BenCat07** [comment]
welcomeback btw

**Comment by LightPower392** [comment]
After this is adding more tooltips.

**Comment by LightPower392** [comment]
Can we get a review of this
@TotallyNotElite

**Comment by TotallyNotElite** [comment]
I'm currently very busy with another project, I'll request other reviewers for you.

**Review by BenCat07 — APPROVED** [review]
Tested, looking good and is functional.

**Pull request merged**
