### PR TITLE
Add IPC support to autoparty

### PR DESCRIPTION
**Pull request by delimeats-ch**

### CODE REVIEW

**Comment by delimeats-ch** [comment]
This doesn't work

**Comment by delimeats-ch** [comment]
Looks like that was all that needed fixing

**Review by iraizo — DISMISSED** [review]
Tested this and seems to work fine all bots joined one specific game, the code also seems fine by taking a quick look of it, LGTM.

**Comment by delimeats-ch** [comment]
The change callback actually won't load hosts from the configured list when IPC mode is disabled since it's not reflected yet so I'm just gonna remove that actually

**Review by iraizo — APPROVED** [review]

**Pull request merged**
