### PR TITLE
Clean up the menu

### PR DESCRIPTION
**Pull request by G-4-M-3-R**

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
In my opinion we didn't need another complete menu overhaul, but here we go again :roll_eyes:

**Comment by DavidStojko** [comment]
Honestly his one looks much better

**Review by BenCat07 — APPROVED** [review]
LGTM


However, there will be some upcoming changes that conflict, so we should wait those out first

**Comment by BenCat07** [comment]
this was merged

**Pull request closed without merging**
