### PR TITLE
Remove unfunny features

### PR DESCRIPTION
**Pull request by d3fc0n6**
epic meowhook code maybe soon if accept yes

### CODE REVIEW

**Review by TotallyNotElite — APPROVED** [review]
based

**Comment by d3fc0n6** [comment]
> based

yep I know, truly based

**Review by aUniqueUser — APPROVED** [review]
@TotallyNotElite can i merge

**Review by BenCat07 — APPROVED** [review]
epic

**Review by iraizo — APPROVED** [review]
too based

**Pull request merged**
