### PR TITLE
Fix nospread failing in alot of cases

### PR DESCRIPTION
**Pull request by BenCat07**

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
Amazing work!

https://t.me/nullworks/511230
https://t.me/nullworks/511266

**Comment by BenCat07** [comment]
(how it looked previously)

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
Doesn't fix it: https://t.me/nullworks/511370

**Comment by BenCat07** [comment]
fixed it tho

**Pull request merged**
