### PR TITLE
Add legit backtrack to autobackstab

### PR DESCRIPTION
**Pull request by crwn1337**
[I wanted this to be added a long time ago](https://github.com/nullworks/cathook/issues/651#issuecomment-449452131), but it never got added

Its just the doBacktrackStab() method, but the for angle loop removed (basically triggerbot, but the code is trash). I removed it since a lot of server mods ban you for doing a quick spin and it looks suspicious.

I dont expect this to be merged, since the code is just copy pasted (and it could be made better)

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
LGTM

**Comment by crwn1337** [comment]
tabs got somehow messed up, im too lazy to fix xd

**Comment by BenCat07** [comment]
Use spsces in xml and not tabs

**Comment by BenCat07** [comment]
Won't merge if broken

**Comment by TotallyNotElite** [comment]
@BenCat07 did you just close this? Wtf? Maybe give him time to correct his mistake?

**Comment by BenCat07** [comment]
He could reopen it once fixed

**Comment by TotallyNotElite** [comment]
> He could reopen it once 

Actually no he can't. Only maintainers can do that. Anyway, your are supposed to keep it open and use the "review" function in GitHub to request changes.

**Comment by crwn1337** [comment]
I fixed the formatting

**Pull request merged**
