### PR TITLE
Added horizontal healthbars

### PR DESCRIPTION
**Pull request by LightPower392**
Adding the request of [#341 ](https://github.com/nullworks/cathook/issues/341) Adds two healthbar modes in addition to the already existing vertical. There is horizontal at the top of the esp and at the bottom.

### CODE REVIEW

**Comment by LightPower392** [comment]
In addition to what was already stated, I realized that the auto-deadringer was broken and fixed it by deleting a single `!`
Also, could I get an update on the state of the tooltip pull request.

**Comment by TotallyNotElite** [comment]
I'll look into it when on pc

**Comment by BenCat07** [comment]
> Looks good, maybe add some comments indicating what healthbar == 1 or healthbar == 2 means in the code.

@LightPower392 Will you look into this or no?

**Comment by LightPower392** [comment]
> Will you look into this or no?

done

**Comment by BenCat07** [comment]
Thanks for your changes :)

**Pull request merged**
