### PR TITLE
QoL and readability improvement

### PR DESCRIPTION
**Pull request by NotAnUser1**
Approved by 9 out of 10 bencats and tnes

### CODE REVIEW

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
> Approved by 9 out of 10 bencats and tnes

Apparently I am the 10th TNE. I don't like it when words are capitalized for no reason.
See #1047, which introduced sentence case on purpose.

**Comment by NotAnUser1** [comment]
well, some were capitalized and some were not, so I made them all pleasing to (my) eyes

**Comment by TotallyNotElite** [comment]
I understand that and appreciate the effort, but I don't think I can accept this into Cathook in its current state. If someone wants to add a toggle option between the 2 types and PR that, that'd work.

Also, these variables don't exist any more, I'm not sure why you readded them.
https://github.com/nullworks/cathook/pull/1118/commits/e7a195f0806f802be09a9e2e70ac2b4199207f8c#diff-a410e5e92202d82e495e035ccab4cc8eR127-R136

**Comment by NotAnUser1** [comment]
idk I thought I was just the one who didn't see them, I don't think I know enough to make an option like that, but we'll see

**Comment by TotallyNotElite** [comment]
Going to close this, replaced by a different PR.

**Pull request closed without merging**
