### PR TITLE
Fix no visual builds not compiling

### PR DESCRIPTION
**Pull request by BenCat07**
also disconnect stuff

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
Can you use a proper title for historical purposes?

**Comment by BenCat07** [comment]
i have to retain the spirit of the title

**Comment by TotallyNotElite** [comment]
Also, can you remove the merge commit? 
image   ^ this one. Use rebases instead.

**Comment by BenCat07** [comment]
you mean "can you force push to your branch and ruin git history?"

**Comment by TotallyNotElite** [comment]
> you mean "can you force push to your branch and ruin git history?"

I'm not sure what git history you're ruining here. I asked you to remove a merge commit.

**Comment by BenCat07** [comment]
> > you mean "can you force push to your branch and ruin git history?"
> 
> I'm not sure what git history you're ruining here. I asked you to remove a merge commit.

i have to force push

**Comment by TotallyNotElite** [comment]
> > I'm not sure what git history you're ruining here. I asked you to remove a merge commit.
> 
> i have to force push

Ok? What's the big deal? I'm asking you to remove a commit from your pull request, not rewriting the history on a major release branch.

**Comment by BenCat07** [comment]
yep

**Pull request merged**
