### PR TITLE
updated MAX_PLAYERS to 100 and change boost::unordered_flat_map to std::unordered_map to prevent boost issues

### PR DESCRIPTION
**Pull request by rosne-gamingyt**

### CODE REVIEW

**Comment by aUniqueUser** [comment]
What issues is unordered_flat_map causing?

**Comment by rosne-gamingyt** [comment]
> What issues is unordered_flat_map causing?
> 
> https://github.com/nullworks/cathook/pull/1834 CI issue it seems
> 
> Why not just update to the latest version of boost? It is better solution then forcing use of an old version

well, cathook is stable on this version of boost and there is no reason to really upgrade. plus, I have seen people have this error too, not only circleci

**Comment by BenCat07** [comment]
boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...

**Comment by rosne-gamingyt** [comment]
> boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...

I guess just merge it as a temporary fix, until you can fix the issue

**Comment by pixelwarrior99** [comment]
> > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> 
> So remove nullnexus? It's broken and causes about 90% of the current crashes.

Yes this is true

**Comment by rosne-gamingyt** [comment]
> > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> 
> So remove nullnexus? It's broken and causes about 90% of the current crashes.

we don't need to remove nullnexus, it's pretty useful if you think about it.

**Comment by pixelwarrior99** [comment]
> > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> > 
> > 
> > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> 
> we don't need to remove nullnexus, it's pretty useful if you think about it.

How so is it useful  you removed it off of ur fork

**Comment by rosne-gamingyt** [comment]
> > > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> 
> > > 
> 
> > > 
> 
> > > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> 
> > 
> 
> > we don't need to remove nullnexus, it's pretty useful if you think about it.
> 
> 
> 
> How so is it useful  you removed it off of ur fork

because it's currently broken? if it gets fixed maybe I'll add it back

**Comment by pixelwarrior99** [comment]
> > > > > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > we don't need to remove nullnexus, it's pretty useful if you think about it.
> > > 
> > > 
> > > How so is it useful  you removed it off of ur fork
> > 
> > 
> > because it's currently broken? if it gets fixed maybe I'll add it back
> 
> You know it's actually not. You're just using it wrong. I only say its "broken" because the current devs do not support it.

Yeah nothing is stop you form hosting a nellnex server

**Comment by rosne-gamingyt** [comment]
> > > > > > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > we don't need to remove nullnexus, it's pretty useful if you think about it.
> > > > 
> > > > 
> > > > How so is it useful  you removed it off of ur fork
> > > 
> > > 
> > > because it's currently broken? if it gets fixed maybe I'll add it back
> > 
> > 
> > You know it's actually not. You're just using it wrong. I only say its "broken" because the current devs do not support it.
> 
> Yeah nothing is stop you form hosting a nellnex server

I do not want to "form" a "nellnex" server, lol

**Comment by UndefindedUser25** [comment]
> > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> > 
> > 
> > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> 
> we don't need to remove nullnexus, it's pretty useful if you think about it.

but it probably broke cathook

**Comment by lamppost53** [comment]
> > > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> > > 
> > > 
> > > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> > 
> > 
> > we don't need to remove nullnexus, it's pretty useful if you think about it.
> 
> but it probably broke cathook

how would it break cathook exactly?

**Comment by AOriginalUsername** [comment]
> > > > > boost is generally broken, we can't upgrade due to Nullnexus breaking, but the flat map is alot better performance wise aswell...
> > > > 
> > > > 
> > > > So remove nullnexus? It's broken and causes about 90% of the current crashes.
> > > 
> > > 
> > > we don't need to remove nullnexus, it's pretty useful if you think about it.
> > 
> > 
> > but it probably broke cathook
> 
> how would it break cathook exactly?

This Pull Request will never get merged it doesn't fix anything

boost::unordered_flat_map are better then std::unordered_map

**Pull request closed without merging**
