### PR TITLE
fix compile

### PR DESCRIPTION
**Pull request by crwn1337**

### CODE REVIEW

**Comment by crwn1337** [comment]
image
****

**Comment by BenCat07** [comment]
The heck, how did that happen? It compiled before

**Comment by BenCat07** [comment]
Actually this is only an issue in your partciular build, as CircleCI compiles it just fine

**Comment by crwn1337** [comment]
it built fine for me before as well i think some update broke it

**Comment by BenCat07** [comment]
Here is what happened: It works fine on normal cathook since everything that includes the file also includes <optional>. The issue is that you have some changes that either Add a file that accesses entitycache.hpp and does not include <optional>, or you cleaned up some includes in an existing file, causing it to error.

No update broke it, as can be seen by the fact that CircleCI compiled cathook successfully on the master branch.

**Comment by crwn1337** [comment]
yes it worked fine for me yesterday until i updated my system, i think some package update broke it is what i meant

**Pull request merged**
