### PR TITLE
UI Colors tab

### PR DESCRIPTION
**Pull request by buyBread**
Screenshot from 2019-10-24 21-41-14

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
Very cool! Does the color selector even work tho :thinking:

**Comment by buyBread** [comment]
Yes.
ss

**Comment by TotallyNotElite** [comment]
> Yes.
> ss

No I mean the color selector gui.

**Comment by buyBread** [comment]
Well yeah I made that theme using this Tab.

**Comment by BenCat07** [comment]
This is epic. i Approve, thank you :)

**Comment by buyBread** [comment]
2nd row includes all the elements that you can interact with (enable/disable features, change modes etc.) + I don't think that the larger "Other Container elements" box will fit.
I could try making the rows vertical tomorrow though.

**Comment by TotallyNotElite** [comment]
Great. Thanks a lot! This is the kind of stuff developers are too lazy to do :D

**Comment by buyBread** [comment]
Screenshot from 2019-10-25 07-32-25

**Pull request merged**
