### PR TITLE
""Fix"" locale issue caused by steam

### PR DESCRIPTION
**Pull request by BenCat07**
just make the popup not appear lol

### CODE REVIEW

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
The if statement seems to be incorrect.

**Comment by BenCat07** [comment]
my brain is cosmic

**Review by TotallyNotElite — APPROVED** [review]
there we go

**Comment by BenCat07** [comment]
fixing ci

**Comment by TotallyNotElite** [comment]
> fixing ci

Don't fix something that isn't broken? What are you fixing

**Pull request merged**
