### PR TITLE
canFaceStab changes

### PR DESCRIPTION
**Pull request by iraizo**
I added 2 of the suggestion https://github.com/nullworks/cathook/issues/735#issuecomment-503894644 provided.

### CODE REVIEW

**Comment by iraizo** [comment]
^ No mini crit check, jarate check its 5 AM.

**Review by BenCat07 — DISMISSED** [review]
LGTM

**Comment by BenCat07** [comment]
maybe add minicrit boosted on local_e check or something tho

**Comment by iraizo** [comment]
> maybe add minicrit boosted on local_e check or something tho

What about `TF_COND_CRITBOOSTED`

**Comment by iraizo** [comment]
Nevermind `TFCond_MiniCritOnKill` works just as well I guess.

**Comment by iraizo** [comment]
@BenCat07 Does this look good? I cant really test it since cathook is now crashing on every install.

**Comment by BenCat07** [comment]
> @BenCat07 Does this look good? I cant really test it since cathook is now crashing on every install.

hold up, what

**Comment by iraizo** [comment]
> > @BenCat07 Does this look good? I cant really test it since cathook is now crashing on every install.
> 
> hold up, what

Yeah, reinstalled manjaro using a stable kernel and im still crashing. ```
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Error while reading shared library symbols for /usr/lib32/libpthread.so.0:
Cannot find user-level thread for LWP 3076: generic error
0xf7f82549 in __kernel_vsyscall ()
Calling dlopen
Cannot find user-level thread for LWP 3430: generic error
An error occurred while in a function called from GDB.
Evaluation of the expression containing the function
(dlopen) will be abandoned.
When the function is done executing, GDB will silently stop.
Calling dlerror
Selected thread is running.
./attach: line 45:  3393 Aborted                 (core dumped) gdb -n -q -batch -ex "attach $proc" -ex "echo \033[1mCalling dlopen\033[0m\n" -ex "call ((void()(const char, int))dlopen)("$FILENAME", 1)" -ex "echo \033[1mCalling dlerror\033[0m\n" -ex "call ((char(*)(void))dlerror)()" -ex "detach" -ex "quit"
``` or are you refering to the code?

**Comment by BenCat07** [comment]
I meant the crash, and this one is a new one, never seen that one

**Comment by iraizo** [comment]
> I meant the crash, and this one is a new one, never seen that one
Anything you want me to provide to help you figure out what it could cause?

**Comment by BenCat07** [comment]
fully update system ig?

**Comment by iraizo** [comment]
yes

**Comment by TotallyNotElite** [comment]
Do you mind opening an issue for the crash, so it can be tracked properly?

**Comment by iraizo** [comment]
> Do you mind opening an issue for the crash, so it can be tracked properly?

Sure thing, can this pr be merged?

**Review by TotallyNotElite — APPROVED** [review]
LGTM

**Pull request merged**
